apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s
  labels:
    app: k8s     
spec:
  selector:
    matchLabels:
      app: k8s
  replicas: 1 
  template: 
    metadata:
      labels:
        app: k8s     
    spec:
      containers:
        - name: k8s
          # image: gauridurugkar/k8s:latest
          image: test:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000        
          volumeMounts:
            - name: k8s-config
              mountPath: /usr/share
      volumes:
        - name: k8s-config
          configMap:
            name: k8s
